apiVersion: apps/v1
kind: Deployment
metadata:
  name: langgraph-worker
  labels:
    app: langgraph-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: langgraph-worker
  template:
    metadata:
      labels:
        app: langgraph-worker
    spec:
      containers:
      - name: langgraph-worker
        image: langgraph-worker:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-credentials
              key: openai-api-key
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://jaeger-service:4318"
        - name: OTEL_SERVICE_NAME
          value: "langgraph-worker"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import kafka; print('ready')"
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-credentials
type: Opaque
data:
  openai-api-key: eW91ci1vcGVuYWktYXBpLWtleQ==  # base64 encoded placeholder